"""empty message

Revision ID: 20b6609c26e0
Revises: None
Create Date: 2015-04-02 01:46:51.782253

"""

# revision identifiers, used by Alembic.
revision = '20b6609c26e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pod_number', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('addr_wan', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr_wan'),
    sa.UniqueConstraint('pod_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    ### end Alembic commands ###
