"""empty message

Revision ID: 349b020fbd82
Revises: 27775865213f
Create Date: 2015-04-06 22:21:23.055880

"""

# revision identifiers, used by Alembic.
revision = '349b020fbd82'
down_revision = '27775865213f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
