"""empty message

Revision ID: 4cd123954d23
Revises: None
Create Date: 2015-03-31 23:57:17.604716

"""

# revision identifiers, used by Alembic.
revision = '4cd123954d23'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pod_number', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('wan_ip', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_number'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wan_ip')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    ### end Alembic commands ###
